if 5==5!=6 :
    print('ertr')
name=input('Enter name: ')
print(name.isdigit())
print(name.removeprefix('c'))
print(name.removesuffix('u'))
#name[0]=8
print(name[3])
print(name[0].lower())
print(name)
print(name.find('c',0,4))
print(name.find('c',4,0))
print(name.find(' '))
print(name.index('c'))
print(name.replace('c','d',5))
print(name.replace('cham','dec'))
print(name[2].replace('a','g'))
print(name)
name=name.replace('c','d')

print(name)
#name[2]= name[2].replace('a','g')
print(name)
print(name.count('a'))
print(name.count('a',0,8))
print(name.isdigit())